List<Map<String, dynamic>> foodData = [
  <String, dynamic>{
    'foodName': 'Cheese Burger',
    'restaurantName': 'Cheesy Mozarella',
    'img': 'assets/images/cheese_burger.png',
    'cardColor': 'F5FFB1',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'Piece Cake',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/piece_cake.png',
    'cardColor': 'ffc9d6',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'French Fries',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/french_fries.png',
    'cardColor': 'de8786',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'Italian Pizza',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/pizza_slice.png',
    'cardColor': 'fdf1c7',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'Fish Sushi',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/fish_sushi.png',
    'cardColor': 'ffc0ae',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'Shawarma',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/shawarma.png',
    'cardColor': 'cae6a4',
    'price': 99,
  },
  <String, dynamic>{
    'foodName': 'Hot Dog',
    'restaurantName': 'Sassacus Inside',
    'img': 'assets/images/hot_dog.png',
    'cardColor': 'cb9d9d',
    'price': 99,
  },
];
